"""Public source metadata kept independent of parser and network dependencies."""

EXTRA_SOURCES = {'indiana': {'id': 'indiana',
             'label': 'Indiana',
             'jurisdiction': 'IN',
             'method': 'Annual report',
             'homepage': 'https://www.in.gov/attorneygeneral/consumer-protection-division/id-theft-prevention/security-breaches/'},
 'iowa': {'id': 'iowa',
          'label': 'Iowa',
          'jurisdiction': 'IA',
          'method': 'Annual notices',
          'homepage': 'https://www.iowaattorneygeneral.gov/for-consumers/security-breach-notifications'},
 'maine': {'id': 'maine',
           'label': 'Maine',
           'jurisdiction': 'ME',
           'method': 'Public notices',
           'homepage': 'https://www.maine.gov/ag/consumer-protection/data-security-breaches'},
 'north_dakota': {'id': 'north_dakota',
                  'label': 'North Dakota',
                  'jurisdiction': 'ND',
                  'method': 'Public notices',
                  'homepage': 'https://attorneygeneral.nd.gov/consumer-resources/data-breach-notices'},
 'oklahoma': {'id': 'oklahoma',
              'label': 'Oklahoma state government',
              'jurisdiction': 'OK',
              'method': 'Government incidents',
              'homepage': 'https://oklahoma.gov/omes/divisions/information-services/cyber-command/notices/cybersecurity-breaches.html'},
 'maryland': {'id': 'maryland',
              'label': 'Maryland',
              'jurisdiction': 'MD',
              'method': 'Public notice lists',
              'homepage': 'https://oag.maryland.gov/resources-info/Pages/security-breach-notices.aspx'},
 'new_jersey': {'id': 'new_jersey',
                'label': 'New Jersey',
                'jurisdiction': 'NJ',
                'method': 'Public notices',
                'homepage': 'https://www.cyber.nj.gov/threat-landscape/public-data-breaches'},
 'wisconsin': {'id': 'wisconsin',
               'label': 'Wisconsin',
               'jurisdiction': 'WI',
               'method': 'Public notices',
               'homepage': 'https://datcp.wi.gov/Pages/Programs_Services/DataBreaches.aspx'},
 'montana': {'id': 'montana',
             'label': 'Montana',
             'jurisdiction': 'MT',
             'method': 'Public notices',
             'homepage': 'https://dojmt.gov/office-of-consumer-protection/reported-data-breaches/'},
 'washington': {'id': 'washington',
                'label': 'Washington',
                'jurisdiction': 'WA',
                'method': 'Public notices',
                'homepage': 'https://www.atg.wa.gov/data-breach-notifications'},
 'south_carolina': {'id': 'south_carolina',
                    'label': 'South Carolina',
                    'jurisdiction': 'SC',
                    'method': 'Public notices',
                    'homepage': 'https://consumer.sc.gov/identity-theft-unit/security-breach-notices'},
 'delaware': {'id': 'delaware',
              'label': 'Delaware',
              'jurisdiction': 'DE',
              'method': 'Public notices',
              'homepage': 'https://attorneygeneral.delaware.gov/fraud/cpu/securitybreachnotification/database/'},
 'new_hampshire': {'id': 'new_hampshire',
                   'label': 'New Hampshire',
                   'jurisdiction': 'NH',
                   'method': 'Public notices',
                   'homepage': 'https://www.doj.nh.gov/citizens/consumer-protection-antitrust-bureau/security-breach-notifications'},
 'texas': {'id': 'texas',
           'label': 'Texas',
           'jurisdiction': 'TX',
           'method': 'Official public JSON',
           'homepage': 'https://oag.my.site.com/datasecuritybreachreport/apex/DataSecurityReportsPage'},
 'sec': {'id': 'sec',
         'label': 'SEC EDGAR',
         'jurisdiction': 'US',
         'method': '8-K Item 1.05 filings',
         'homepage': 'https://www.sec.gov/edgar/search/'}}

# Active adapters follow the currently published source surfaces.
EXTRA_SOURCES['maryland']['method'] = 'Official public JSON'
EXTRA_SOURCES['new_jersey']['method'] = 'Official public HTML notices'
EXTRA_SOURCES['new_hampshire']['method'] = 'Official public document API'
EXTRA_SOURCES['sec']['method'] = 'Official Item 1.05 search metadata'
